services:
  # CivicPulse - Combined Backend + Frontend
  - type: web
    name: civicpulse
    runtime: node
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && cd frontend && npm install --legacy-peer-deps --include=dev && npx ng build && cd ..
    startCommand: node backend/server.js
    healthCheckPath: /api/test
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: NPM_CONFIG_PRODUCTION
        value: false
    autoDeploy: true
