services:
  # Backend Web Service
  - type: web
    name: civicpulse-backend
    runtime: node
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/test
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        sync: false
    autoDeploy: true

  # Frontend Static Site
  - type: static
    name: civicpulse-frontend
    env: static
    region: oregon
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist/civicpulse-frontend
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    autoDeploy: true
